name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      # Define the artifact name to share between jobs
      artifacts: ${{ needs.build.outputs.artifacts }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install

    - name: Create dist directory if not exists
      run: |
        if [ ! -d "dist" ]; then
          mkdir dist
        fi

    - name: Minify JavaScript
      run: npm run minify

    - name: Run Tests
      run: npm test

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: dist

  dockerize:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: actions/setup-docker@v2
      with:
        dockerfile: Dockerfile
        context: .

    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: artifacts
        path: dist

    - name: Build Docker Image
      run: |
        docker build -t docker.pkg.github.com/rm0357/js-app/simple-web-app:${{ github.sha }} .
      env:
        DOCKER_REGISTRY_USERNAME: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
        DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

    - name: Push Docker Image
      run: |
        docker login docker.pkg.github.com -u $DOCKER_REGISTRY_USERNAME -p $DOCKER_REGISTRY_PASSWORD
        docker push docker.pkg.github.com/rm0357/js-app/simple-web-app:${{ github.sha }}
      env:
        DOCKER_REGISTRY_USERNAME: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
        DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
