name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      artifacts: ${{ needs.build.outputs.artifacts }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install

    - name: Create dist directory if not exists
      run: |
        if [ ! -d "dist" ]; then
          mkdir dist
        fi

    - name: Minify JavaScript
      run: npm run minify

    - name: Run Tests
      run: npm test

    - name: Save package-lock.json as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: |
          package-lock.json
          dist

  dockerize:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-qemu-action@v2

    - name: Set up QEMU
      uses: docker/setup-buildx-action@v2

    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: artifacts

    - name: Build and Push Docker Image
      run: |
        docker build -t rm0357/js-app:${{ github.sha }} .
        echo $DOCKER_REGISTRY_PASSWORD | docker login -u $DOCKER_REGISTRY_USERNAME --password-stdin
        docker push rm0357/js-app:${{ github.sha }}
      env:
        DOCKER_REGISTRY_USERNAME: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
        DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
