name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      artifacts: ${{ needs.build.outputs.artifacts }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install

    - name: Create dist directory if not exists
      run: |
        if [ ! -d "dist" ]; then
          mkdir dist
        fi

    - name: Minify JavaScript
      run: npm run minify

    - name: Run Tests
      run: npm test

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: dist

  dockerize:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-qemu-action@v2

    - name: Set up QEMU
      uses: docker/setup-buildx-action@v2

    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: artifacts
        path: dist

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: true
        tags: docker.pkg.github.com/rm0357/js-app/simple-web-app:${{ github.sha }}
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
